### ISSUE TITLE
User Story 3 - User can get all favorites

### ISSUE THREAD

**Issue by joshsherwood1** [MackHalliday/play-play-express#3]
As a user, I can make a GET request `api/v1/favorites`. If the GET request is successful, I see a JSON response with all favorite records in the favorite table database.  For each record, I should see the id, songTitle, artistName, genre, and rating. See requirements below with specific requirements for request and response. 

- [x] Complete the endpoint
- [x] Set up favorite model
- [x] Testing 
- [x] Feature deployed to Heroku
- [x] Update README with information about endpoint

**Request**
``` 
GET /api/v1/favorites
Content-Type: application/json
Accept: application/json

```
**Successful Response**
```
[
  {
    "id": 1,
    "title": "We Will Rock You",
    "artistName": "Queen"
    "genre": "Rock",
    "rating": 88
  },
  {
    "id": 2,
    "title": "Careless Whisper",
    "artistName": "George Michael"
    "genre": "Pop",
    "rating": 93
  }
]
```

**Comment by MackHalliday** [comment]
Started solo spike under get_all_favorites_MH. Endpoint is working. 

Created favorite model to handle database call. 

Need to finish testing. Having issues creating test records for database.

**Comment by MackHalliday** [comment]
Deployed to Heroku!
