### ISSUE TITLE
User Story 4 - User can add a new favorite

### ISSUE THREAD

**Issue by joshsherwood1** [MackHalliday/play-play-express#4]
As a user, I can make a POST request to the endpoint `api/v1/favorites`. In the body of the POST request, I must include a song title and can optionally include an artist. If the POST request is successful, I see a JSON response with newly posted record for the song and a 201 status. If the user submit invalid information in the POST request body, I should receive a 400 status code and receive a JSON response error message. 

This endpoint uses MusixMatch API to get song information using song and optionally artist passed in the POST body request. See requirements below with specific requirements for request and response. 

- [x] Complete endpoint
- [x] Account for sad paths
- [x] Testing including sad path
- [x] Feature deployed to Heroku
- [x] Update README with information about endpoint

**Request**
``` 
POST /api/v1/favorites
Content-Type: application/json
Accept: application/json
body:
{
  "title": "We Will Rock You"
}

```
**Successful Response**
```
status: 201

{
  "id": 1,
  "title": "We Will Rock You",
  "artistName": "Queen"
  "genre": "Rock",
  "rating": 88
}
```

**Unsuccessful Response**
```
status: 400

 {
  "message": "Song does not exist"
 }
```

**Comment by MackHalliday** [comment]
**Title: POST api/v1/favorites** 
As a user, I can send a POST request to `api/v1/favorites` to create a new favorite song. 

Details 
- Request params 
  - Song title (required) 
  - Artist (optional) 
 
**Success Response** 
``` 
{ 
 id: 1, 
 songName: "Example Song", 
 artistName: "Example Artist", 
 rating: 10, 
 genre: "Example Genre",
}
``` 
**Unsuccessful Response**
```
status: 404
```

**Resources**
Example Resouces

**Comment by MackHalliday** [comment]
Solo spike completed.

**Comment by MackHalliday** [comment]
Deployed to Heroku!
