### ISSUE TITLE
User Story 5 - User can get a favorite

### ISSUE THREAD

**Issue by joshsherwood1** [MackHalliday/play-play-express#5]
As a user, I can access an API endpoint that gets a favorite song. Id needs to be included in URI to access the record. The response should include song information, including a song title, artist name, rating, genre, and id. If id does not exist, an error message with a 404 status code and error message indicating that favorite record does not exist. See requirements below with specific requirements for request and response. 

- [x] Complete the endpoint
- [x] Testing including sad path (when id does not exist, error message is sent)
- [x] Feature deployed to Heroku
- [x] Update README with information about endpoint

**Request**
``` 
GET /api/v1/favorites/:id
Content-Type: application/json
Accept: application/json

```
**Successful Response**
SHOULD IT BE NESTED IN ARRAY?
```
  {
    "id": 1,
    "title": "We Will Rock You",
    "artistName": "Queen"
    "genre": "Rock",
    "rating": 88
  }
```

**Unsuccessful Response**
```
 status: 404
```

**Comment by MackHalliday** [comment]
Deployed to Heroku!
