### ISSUE TITLE
User Story 6 - User can delete a favorite

### ISSUE THREAD

**Issue by joshsherwood1** [MackHalliday/play-play-express#6]
As a user, I can make a DELETE request to the endpoint `/api/v1/favorites/:id`. The favorite record's ID should be included in the URI. If the DELETE request is successful, I should receive an 204 status code. If the user submits an ID that does not exist, I should receive a 404 status code.  See requirements below with specific requirements for request and response. 

- [x] Complete the endpoint
- [x] Testing including sad path
- [x] Feature deployed to Heroku
- [x] Update README with information about endpoint

**Request**
``` 
DELETE /api/v1/favorites/:id
Content-Type: application/json
Accept: application/json

```
**Successful Response** 
``` 
status code: 204
```

**Unsuccessful Response** 
``` 
status code: 404
```

**Comment by MackHalliday** [comment]
Deployed to Heroku!
